#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Illuminate\Console\Application;
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;

$container = new Container();
$dispatcher = new Dispatcher();
$version = "5.6";

$app = new Application($container, $dispatcher, $version);

$app->add(new App\DumpMigrationsCommand());

$app->run();